# Generated by Django 6.1 on 2026-09-02 13:59

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plataforma', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('empresa', models.CharField(max_length=255, verbose_name='Empresa')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('status', models.CharField(choices=[('ENVIADO', 'Enviado'), ('REJEITADO', 'Rejeitado'), ('ENTREVISTA', 'Entrevista'), ('PROPOSTA', 'Proposta Recebida'), ('APROVADA', 'Aprovada')], default='ENVIADO', max_length=20, verbose_name='Status')),
                ('plataforma', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='Plataforma', to='plataforma.plataforma')),
            ],
            options={
                'verbose_name': 'Candidatura',
                'verbose_name_plural': 'Candidaturas',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='HistoricalCandidatura',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Atualizado em')),
                ('empresa', models.CharField(max_length=255, verbose_name='Empresa')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('status', models.CharField(choices=[('ENVIADO', 'Enviado'), ('REJEITADO', 'Rejeitado'), ('ENTREVISTA', 'Entrevista'), ('PROPOSTA', 'Proposta Recebida'), ('APROVADA', 'Aprovada')], default='ENVIADO', max_length=20, verbose_name='Status')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plataforma', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='plataforma.plataforma')),
            ],
            options={
                'verbose_name': 'historical Candidatura',
                'verbose_name_plural': 'historical Candidaturas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
