# Generated by Django 6.1 on 2026-09-02 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatura', '0001_initial'),
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatura',
            name='plataforma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidaturas', to='plataforma.plataforma'),
        ),
    ]
